Add more EEAs to Java collection objects
lastnpe/eclipse-null-eea-augments pull request #109
Opened 2020-10-31 17:35 UTC by wborn

While using the EEAs I was missing annotations on some commonly used collection classes.

So I've added more annotations in this PR for:

* ArrayList
* Collection
* HashMap
* HashSet
* LinkedList
* List
* Map
* Set
* ConcurrentHashMap

2020-10-31 22:34 UTC, jason-faust commented
@J-N-K Eyeballing this it looks ok, how do you want to handle accepting this?

2020-11-01 09:07 UTC, J-N-K requested changes

2020-11-01 09:07 UTC, J-N-K commented on libraries/java/java/util/Set.eea
> + <T:Ljava/lang/Object;>([T1T;)[1T1T;
See above. Depends on the implementation. In general null-elements in sets are allowed, so a restriction here seems to be wrong.

2020-11-01 09:07 UTC, J-N-K commented
Thanks @wborn

2020-11-01 09:20 UTC, J-N-K commented on libraries/java/java/util/ArrayList.eea
> + (TE;[L1java/lang/Object;I)V
Isn't that method private?

2020-11-01 09:25 UTC, J-N-K commented on libraries/java/java/util/Collection.eea
> + ()[1L1java/lang/Object;
`Collection` in general allows `null` elements, so a non-null-array of (infered nullable) `Object` seems to be ok

2020-11-01 09:27 UTC, J-N-K commented on libraries/java/java/util/Collection.eea
> + <T:Ljava/lang/Object;>(L1java/util/function/IntFunction<[TT;>;)[T1T;
```suggestion
 <T:Ljava/lang/Object;>(L1java/util/function/IntFunction<[1TT;>;)[1TT;
```

The generator needs to return a non-null-array of the desired type, so if the type is @Nullable, members of the array can be null, the array itself is non-null.

2020-11-01 09:32 UTC, J-N-K commented on libraries/java/java/util/LinkedList.eea
> + <T:Ljava/lang/Object;>([T1T;)[T1T;
see above

2020-11-01 11:25 UTC, wborn commented
I think adding annotations to arrays in Eclipse is a bit buggy.

2020-11-01 12:49 UTC, J-N-K approved these changes

2020-11-01 12:49 UTC, merged