Add servlet-api, xstream EEAs and fix missing javamail from eea-all
lastnpe/eclipse-null-eea-augments pull request #110
Opened 2020-11-01 01:03 UTC by wborn

Adds EEAs for:

* javax.security.auth.callback.CallbackHandler
* javax.servlet.Servlet
* javax.servlet.ServletRequest
* javax.servlet.ServletResponse
* javax.servlet.http.HttpServlet
* javax.servlet.http.HttpServletRequest
* javax.servlet.http.HttpServletResponse
* com.thoughtworks.xstream.XStream
* com.thoughtworks.xstream.converters.ConversionException
* com.thoughtworks.xstream.converters.Converter

Also fixes the javamail EEAs missing from eea-all.

2020-11-03 20:08 UTC, J-N-K commented
I wonder why I never get notifications for this repo (I‘m „watching“ it). Will have a look in the next days. Please ping me if I forget.

2020-11-04 15:56 UTC, J-N-K requested changes

2020-11-04 15:56 UTC, J-N-K commented on libraries/xstream/com/thoughtworks/xstream/XStream.eea
> + ([L0java/lang/String;)V
```suggestion
 ([0Ljava/lang/String;)V
```

A null-array is allowed, but the content needs to be non-null, otherwise `getRegExpPatterns` in `WildcardTypePermission` throws an NPE

2020-11-04 15:56 UTC, J-N-K commented on libraries/servlet-api/javax/servlet/ServletResponse.eea
> + (L0java/lang/String;)V
Not sure here: a null-value for the encoding is alloes in `ServletResponse` but not in `ServletRequest`? Can you check again?

2020-11-04 20:48 UTC, wborn commented on libraries/xstream/com/thoughtworks/xstream/XStream.eea
> + ([L0java/lang/String;)V
I now know how to properly annotate these arrays. :smile:

2020-11-04 20:49 UTC, wborn commented on libraries/servlet-api/javax/servlet/ServletResponse.eea
> + (L0java/lang/String;)V
It's not very clear but I've made them nullable which seems the most logical.

2020-11-04 20:57 UTC, J-N-K approved these changes

2020-11-05 05:48 UTC, merged