add (complete) CompletionStage & Executor and (some) EEA
lastnpe/eclipse-null-eea-augments pull request #42
Opened 2017-10-03 15:30 UTC by vorburger

also Executor (easy) and amend CompletableFuture

also includes CompletionStageWrapper Executor bug (?) illustration

2017-11-02 18:30 UTC, vorburger commented
Merging this will need a new headles JDT useable in build available on Maven central so that we can get the https://bugs.eclipse.org/bugs/show_bug.cgi?id=525712 fix.. I'm sure it will be made available eventually.

2020-09-28 16:02 UTC, J-N-K requested changes

2020-09-28 17:09 UTC, vorburger commented on examples/maven/hello/src/main/java/ch/vorburger/nulls/examples/hello/CompletionStageWrapper.java
> +package ch.vorburger.nulls.examples.hello;
:+1: go for it!

2020-09-28 22:38 UTC, vorburger commented on examples/maven/hello/src/main/java/ch/vorburger/nulls/examples/hello/CompletionStageWrapper.java
> +package ch.vorburger.nulls.examples.hello;
but you would have to move it to the respective directory as well, not just change the `package` declaration.

2020-10-04 12:12 UTC, J-N-K approved these changes

2020-10-04 12:13 UTC, merged