Null annotations for java.base/java.lang
lastnpe/eclipse-null-eea-augments pull request #85
Opened 2019-01-18 02:30 UTC by jason-faust

All public and protected members and methods
Authored against OpenJDK 11.0.1 with Eclipse IDE 2018-12

2019-01-18 03:02 UTC, jason-faust commented
I'll try to decipher the build errors tomorrow if I have time.

2019-01-18 03:30 UTC, jason-faust commented
Not sure where to go with this.

Pushing things up to Java 11 requires some plugin changes, however runs into compatibility issues with `java.xml.Bind` being removed from the JDK. But even allowing that the build fails due to the `hello` project.

2020-03-23 20:03 UTC, vorburger commented
The Travis CI build today only builds Java 8 (just fixed it). To proceed with this, you have to contribute a matrix build which also runs it under Java 11. Contributing is very welcome here!

2020-08-25 18:45 UTC, J-N-K requested changes
I did only  check A-E yet, hope to continue tomorrow.

2020-08-25 18:45 UTC, J-N-K commented on libraries/java/java/lang/Class.eea
> + (Ljava/lang/String;)L1java/lang/Class<*>;
This seems wrong. `Class class = Class.forName(null);` throws an NPE, to clearly the parameter must not be null.

2020-08-25 18:45 UTC, J-N-K commented on libraries/java/java/lang/Class.eea
> + ([0L0java/lang/Class<*>;)L1java/lang/reflect/Constructor<TT;>;
```suggestion
 ([1L1java/lang/Class<*>;)L1java/lang/reflect/Constructor<TT;>;
```

Calling `getConstructor´ passes it's `parameters` to `getConstructor0` which does something like `for (Class p : parameter)` which throws an NPE if `parameters` is `null`

2020-08-25 18:45 UTC, J-N-K commented on libraries/java/java/lang/Class.eea
> + ([0L0java/lang/Class<*>;)L1java/lang/reflect/Constructor<TT;>;
```suggestion
 ([1L1java/lang/Class<*>;)L1java/lang/reflect/Constructor<TT;>;
```

see above

2020-08-29 14:44 UTC, J-N-K requested changes
How shall we proceed now?

2020-08-29 14:44 UTC, J-N-K commented on libraries/java/java/lang/Process.eea
> + ()L1java/io/InputStream;
```suggestion
 ()L0java/io/InputStream;
```

in some cases a null input stream is returned

2020-09-06 16:08 UTC, jason-faust commented on libraries/java/java/lang/Class.eea
> + (Ljava/lang/String;)L1java/lang/Class<*>;
You are correct, fixed.

2020-09-06 16:14 UTC, jason-faust commented on libraries/java/java/lang/Class.eea
> + ([0L0java/lang/Class<*>;)L1java/lang/reflect/Constructor<TT;>;
I'm not seeing this being thrown in my testing, but I'm also looking at this with Java 14 at the moment.

2020-09-06 16:22 UTC, jason-faust commented on libraries/java/java/lang/Class.eea
> + ([0L0java/lang/Class<*>;)L1java/lang/reflect/Constructor<TT;>;
Pulled down a copy of the Class source file for JDK 11, code path looks the same, the parameters get looked at in `arrayContentsEq()`, and that has a proper null test.

The below works for me.
```java
package npa;
import java.util.ArrayList;
public class Test {
	public static void main(String[] args) throws Exception {
		Class<ArrayList> a = ArrayList.class;
		System.out.println(a.getConstructor(null));
		System.out.println(a.getDeclaredConstructor(null));
	}
}
```

2020-09-06 16:29 UTC, jason-faust commented on libraries/java/java/lang/Process.eea
> + ()L1java/io/InputStream;
This doesn't return a null value, it returns a null stream, which is still a valid object reference.  See https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/ProcessBuilder.html#redirect-output

2020-09-06 16:31 UTC, J-N-K commented on libraries/java/java/lang/Process.eea
> + ()L1java/io/InputStream;
My fault.

2020-09-06 16:34 UTC, J-N-K commented on libraries/java/java/lang/Class.eea
> + ([0L0java/lang/Class<*>;)L1java/lang/reflect/Constructor<TT;>;
I‘ll re-check that. Pretty sure I had a test-case where I encountered an NPE.

2020-09-06 17:16 UTC, J-N-K approved these changes

2020-09-06 17:23 UTC, J-N-K commented
I guess Travis fails because the methods are missing in Java 8.

2020-09-06 17:26 UTC, jason-faust commented on libraries/java/java/lang/Process.eea
> + ()L1java/io/InputStream;
Don't think there is anything to resolve, the annotations show the return value is non null.  The stream is useless but is valid as far as nulls are conserned.

2020-09-06 17:27 UTC, jason-faust commented
@J-N-K from what @vorburger said, the build needs to be re-configured to support JDK 8 and 11 (and 14), which is impossible with just a simple switch to the matrix build (I tried).

2020-09-08 03:41 UTC, J-N-K commented
The problem will be that we would have to add additional annotations so the tests know what the correct java version for this annotation is, otherwse the Java8 build will always fails.

Another solution would be to have two branches (and two releases), one for Java8 and one for Java 11. This would require cherry-picking compatible changes from the 11-branch to the 8-branch.

The easiest would be to change to Java11 now, since Java8 is now six years old and EOL (at least for Oracle versions),

2020-09-20 11:13 UTC, J-N-K commented
@vorburger @kaikreuzer How can we proceed here? I would suggest to change Travis from Java 8 to Java 11 and merge here. A new release afterwards would be great.

2020-09-23 22:07 UTC, vorburger commented
> @vorburger @kaikreuzer How can we proceed here? I would suggest to change Travis from Java 8 to Java 11 and merge here. A new release afterwards would be great.

Thank You for your interest in [LastNPE.org](http://www.lastnpe.org/)! While I currently do not have the spare cycles to continue contributing to actively maintain this community, I'm very happy to see both of your interests, and would hereby like to empower you to "carry the torch forward" - should you be interested to do so; see #91. Should you accept, feel free to change Travis - and go ahead making any other changes to this project you deem useful.

2020-09-28 15:39 UTC, merged